# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekspor_CSV.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimpanCSV(object):
    def setupUi(self, SimpanCSV):
        SimpanCSV.setObjectName("SimpanCSV")
        SimpanCSV.resize(263, 222)
        self.buttonBox = QtWidgets.QDialogButtonBox(SimpanCSV)
        self.buttonBox.setGeometry(QtCore.QRect(-120, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(SimpanCSV)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SimpanCSV)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(SimpanCSV)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(SimpanCSV)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 30, 181, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(SimpanCSV)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 70, 181, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(SimpanCSV)
        self.comboBox.setGeometry(QtCore.QRect(70, 110, 181, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(SimpanCSV)
        self.buttonBox.accepted.connect(SimpanCSV.accept) # type: ignore
        self.buttonBox.rejected.connect(SimpanCSV.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SimpanCSV)

    def retranslateUi(self, SimpanCSV):
        _translate = QtCore.QCoreApplication.translate
        SimpanCSV.setWindowTitle(_translate("SimpanCSV", "Dialog"))
        self.label_2.setText(_translate("SimpanCSV", "Save as :"))
        self.label_3.setText(_translate("SimpanCSV", "Tag :"))
        self.label_4.setText(_translate("SimpanCSV", "Where :"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SimpanCSV()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
